#!/usr/bin/env bash
set -euo pipefail

# Copies the local V14 verification artifacts into release-evidence/v14.
# Run this only after the full TASK-425 gate succeeds.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEST_DIR="${ROOT_DIR}/release-evidence/v14"

copy_if_present() {
  local src="$1"
  local dest="$2"
  if [[ -e "${src}" ]]; then
    mkdir -p "$(dirname "${dest}")"
    cp -R "${src}" "${dest}"
  fi
}

mkdir -p "${DEST_DIR}/test-results"
mkdir -p "${DEST_DIR}/configs"

copy_if_present "${ROOT_DIR}/platform-benchmarks/build/reports/jmh/jmh-allocation-results.json" \
  "${DEST_DIR}/jmh-allocation-results.json"
copy_if_present "${ROOT_DIR}/platform-benchmarks/build/reports/jmh/jmh-latency-results.json" \
  "${DEST_DIR}/jmh-latency-results.json"

copy_if_present "${ROOT_DIR}/platform-cluster/build/test-results/test" \
  "${DEST_DIR}/test-results/platform-cluster-test"
copy_if_present "${ROOT_DIR}/platform-common/build/test-results/test" \
  "${DEST_DIR}/test-results/platform-common-test"
copy_if_present "${ROOT_DIR}/platform-gateway/build/test-results/test" \
  "${DEST_DIR}/test-results/platform-gateway-test"
copy_if_present "${ROOT_DIR}/platform-tooling/build/test-results/test" \
  "${DEST_DIR}/test-results/platform-tooling-test"
copy_if_present "${ROOT_DIR}/platform-tooling/build/test-results/e2eTest" \
  "${DEST_DIR}/test-results/platform-tooling-e2eTest"

copy_if_present "${ROOT_DIR}/config/venues.toml" "${DEST_DIR}/configs/venues.toml"
copy_if_present "${ROOT_DIR}/config/instruments.toml" "${DEST_DIR}/configs/instruments.toml"
copy_if_present "${ROOT_DIR}/config/strategies.toml" "${DEST_DIR}/configs/strategies.toml"
copy_if_present "${ROOT_DIR}/config/fees.toml" "${DEST_DIR}/configs/fees.toml"
copy_if_present "${ROOT_DIR}/config/risk.toml" "${DEST_DIR}/configs/risk.toml"
copy_if_present "${ROOT_DIR}/config/v14-production-preflight.toml" \
  "${DEST_DIR}/configs/v14-production-preflight.toml"

cat > "${DEST_DIR}/MANIFEST.txt" <<MANIFEST
NitroJEx V14 release evidence archive

Generated by: scripts/archive-v14-release-evidence.sh

Required upstream gates before this archive is valid:
- ./gradlew clean
- ./gradlew check
- ./gradlew e2eTest
- ./gradlew :platform-benchmarks:jmh
- ./gradlew :platform-benchmarks:jmhLatencyReport
- scripts/v14-preflight-check.sh

Archived automated evidence:
- test-results/platform-cluster-test
- test-results/platform-common-test
- test-results/platform-gateway-test
- test-results/platform-tooling-test
- test-results/platform-tooling-e2eTest
- jmh-allocation-results.json
- jmh-latency-results.json
- configs/*.toml

Manual evidence still required before real Coinbase or Binance QA/UAT:
- Binance credential rotation and live FIX session signoff
- two-venue partial-outage and reconciliation rehearsal signoff
- deployment, monitoring, alert routing, failover, disaster recovery, and rollback signoff
MANIFEST

echo "Archived V14 release evidence into ${DEST_DIR}"
